name: Request Environment
description: Request a cloud environment for your application.
title: "[App Name]: "
labels: ["new-subscription", "azure"]
assignees:
  - khowling
body:
  - type: markdown
    attributes:
      value: |
        Complete the form to get access a new environemnt, this will take around 5minutes unless approal is needed!
  - type: input
    id: owner
    attributes:
      label: Environment Owner
      description: This user will get Roll Based Access Control to the environment
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: workload-type
    attributes:
      label: Workload Type
      description: What environment type are you looking for? sandbox for experiments, or Non-Production / Production for releasing your applications.
      options:
        - Non-Production / Production
        - Sandbox
      default: 0
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      label: What connectivity do you need?
      description: This determines if private IP connectivity is required by the workload, or if all external dependencies and access will be routed over the public internet.
      multiple: false
      options:
        - Standalown
        - Connected
  - type: input
    id: existing-sub
    attributes:
      label: Add to existing Subscription
      description: Enter Subscription ID here, otherwise just leave empty
      placeholder: ex. 0000x000-xx00-0000-00xx-00xx00000xxx
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Breif description of the use of the environment?
      description: for learning, for POC, release into Production?
      placeholder: Tell us what you are doing!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
