name: Request Environment
description: Request a cloud environment for your application.
title: "[Name]: "
labels: ["new-subscription", "azure"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - khowling
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: owner
    attributes:
      label: Environment Owner
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Breif description of the use of the environment?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you are doing!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: workload-type
    attributes:
      label: Workload Type
      description: What environment type are you looking for, sandbox for experiments, or production for releasing your application?
      options:
        - Production
        - Sandbox
      default: 0
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      label: What connectivity do you need?
      multiple: false
      options:
        - Standalown
        - Connected
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
